apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wolf.fullname" . }}
  labels:
    {{- include "wolf.labels" . | nindent 4 }}
type: Opaque
stringData:
  master-key: {{ required "masterKey is required" .Values.masterKey | quote }}
  {{- $mode := include "wolf.postgresMode" . }}
  {{- if eq $mode "external" }}
  {{- if not .Values.postgres.external.existingSecret }}
  postgres-dsn: {{ include "wolf.postgresDSN" . | quote }}
  {{- end }}
  {{- else }}
  postgres-password: {{ required "postgres.password is required" .Values.postgres.password | quote }}
  postgres-dsn: {{ include "wolf.postgresDSN" . | quote }}
  {{- end }}
