apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wolf.fullname" . }}
  labels:
    {{- include "wolf.labels" . | nindent 4 }}
type: Opaque
stringData:
  master-key: {{ required "masterKey is required" .Values.masterKey | quote }}
  postgres-password: {{ required "postgres.password is required" .Values.postgres.password | quote }}
  postgres-dsn: {{ printf "postgres://%s:%s@%s-postgres:5432/%s?sslmode=disable" .Values.postgres.username .Values.postgres.password (include "wolf.fullname" .) .Values.postgres.database | quote }}
