package pr

import (
	"context"
	"fmt"
	"os/exec"
	"strings"

	"github.com/alphabravocompany/thewolf/internal/models"
)

// PRRequest holds the information needed to create a PR/MR.
type PRRequest struct {
	RepoPath   string
	BranchName string
	BaseBranch string
	Category   models.Category
	Findings   []models.Finding
	Validation string // "all pass" / "N/M pass"
}

// PRResult holds the outcome of PR creation.
type PRResult struct {
	URL   string
	Error string
}

// CreateGitHubPR creates a GitHub pull request using the gh CLI.
func CreateGitHubPR(ctx context.Context, req PRRequest) (*PRResult, error) {
	title := fmt.Sprintf("[Wolf] Fix %s issues (%d findings)", req.Category, len(req.Findings))
	body := buildPRBody(req)

	cmd := exec.CommandContext(ctx, "gh", "pr", "create",
		"--title", title,
		"--body", body,
		"--base", req.BaseBranch,
		"--head", req.BranchName,
	)
	cmd.Dir = req.RepoPath

	output, err := cmd.CombinedOutput()
	if err != nil {
		return &PRResult{
			Error: fmt.Sprintf("gh pr create: %s: %s", string(output), err),
		}, nil
	}

	url := strings.TrimSpace(string(output))
	return &PRResult{URL: url}, nil
}

// CreateGitLabMR creates a GitLab merge request using the glab CLI.
func CreateGitLabMR(ctx context.Context, req PRRequest) (*PRResult, error) {
	title := fmt.Sprintf("[Wolf] Fix %s issues (%d findings)", req.Category, len(req.Findings))
	body := buildPRBody(req)

	cmd := exec.CommandContext(ctx, "glab", "mr", "create",
		"--title", title,
		"--description", body,
		"--source-branch", req.BranchName,
		"--target-branch", req.BaseBranch,
	)
	cmd.Dir = req.RepoPath

	output, err := cmd.CombinedOutput()
	if err != nil {
		return &PRResult{
			Error: fmt.Sprintf("glab mr create: %s: %s", string(output), err),
		}, nil
	}

	url := strings.TrimSpace(string(output))
	return &PRResult{URL: url}, nil
}

// PushBranch pushes the fix branch to the remote.
func PushBranch(ctx context.Context, repoPath, branchName string) error {
	cmd := exec.CommandContext(ctx, "git", "push", "-u", "origin", branchName) // #nosec G204 -- command is a configured tool name; args sourced from internal config
	cmd.Dir = repoPath
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git push: %s: %w", string(output), err)
	}
	return nil
}

func buildPRBody(req PRRequest) string {
	var sb strings.Builder
	sb.WriteString("## Wolf Automated Fix\n\n")
	sb.WriteString(fmt.Sprintf("**Category:** %s\n", req.Category))
	sb.WriteString(fmt.Sprintf("**Findings Fixed:** %d\n", len(req.Findings)))
	sb.WriteString(fmt.Sprintf("**Validation:** %s\n\n", req.Validation))

	sb.WriteString("### Findings Addressed\n\n")
	for _, f := range req.Findings {
		sb.WriteString(fmt.Sprintf("- **[%s]** %s (`%s:%d`)\n",
			strings.ToUpper(string(f.Severity)), f.Title, f.FilePath, f.LineStart))
	}

	sb.WriteString("\n---\n")
	sb.WriteString("*Generated by [The Wolf](https://github.com/alphabravocompany/thewolf) — AI-Powered Code Analysis & Fix Engine*\n")
	return sb.String()
}
