package pr

import (
	"strings"
	"testing"

	"github.com/alphabravocompany/thewolf/internal/models"
)

func TestBuildPRBody(t *testing.T) {
	tests := []struct {
		name     string
		req      PRRequest
		contains []string
	}{
		{
			name: "basic PR body",
			req: PRRequest{
				Category: models.CategorySAST,
				Findings: []models.Finding{
					{
						Severity:  models.SeverityHigh,
						Title:     "SQL Injection",
						FilePath:  "db.go",
						LineStart: 42,
					},
				},
				Validation: "all pass",
			},
			contains: []string{
				"Wolf Automated Fix",
				"sast",
				"Findings Fixed:** 1",
				"Validation:** all pass",
				"[HIGH]",
				"SQL Injection",
				"db.go:42",
			},
		},
		{
			name: "multiple findings",
			req: PRRequest{
				Category: models.CategorySecrets,
				Findings: []models.Finding{
					{Severity: models.SeverityCritical, Title: "Exposed API key", FilePath: "config.go", LineStart: 10},
					{Severity: models.SeverityHigh, Title: "Hardcoded password", FilePath: "auth.go", LineStart: 25},
				},
				Validation: "2/2 pass",
			},
			contains: []string{
				"secrets",
				"Findings Fixed:** 2",
				"[CRITICAL]",
				"[HIGH]",
				"Exposed API key",
				"Hardcoded password",
			},
		},
		{
			name: "zero findings",
			req: PRRequest{
				Category:   models.CategoryQuality,
				Findings:   []models.Finding{},
				Validation: "N/A",
			},
			contains: []string{
				"quality",
				"Findings Fixed:** 0",
			},
		},
		{
			name: "footer present",
			req: PRRequest{
				Category: models.CategorySAST,
				Findings: []models.Finding{
					{Severity: models.SeverityLow, Title: "Minor", FilePath: "x.go", LineStart: 1},
				},
			},
			contains: []string{
				"Generated by",
				"The Wolf",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			body := buildPRBody(tt.req)
			for _, want := range tt.contains {
				if !strings.Contains(body, want) {
					t.Errorf("buildPRBody() missing %q in output:\n%s", want, body)
				}
			}
		})
	}
}

func TestBuildPRBodyMarkdownStructure(t *testing.T) {
	req := PRRequest{
		Category: models.CategorySAST,
		Findings: []models.Finding{
			{Severity: models.SeverityMedium, Title: "Issue", FilePath: "f.go", LineStart: 1},
		},
		Validation: "pass",
	}
	body := buildPRBody(req)

	// Check markdown headings
	if !strings.Contains(body, "## Wolf Automated Fix") {
		t.Error("missing H2 header")
	}
	if !strings.Contains(body, "### Findings Addressed") {
		t.Error("missing H3 header")
	}
	// Check bullet list
	if !strings.Contains(body, "- **[MEDIUM]**") {
		t.Error("missing bullet list item")
	}
	// Check separator
	if !strings.Contains(body, "---") {
		t.Error("missing separator")
	}
}

func TestPRRequestFields(t *testing.T) {
	req := PRRequest{
		RepoPath:   "/tmp/repo",
		BranchName: "wolf/fix-sast",
		BaseBranch: "main",
		Category:   models.CategorySAST,
		Findings:   nil,
		Validation: "",
	}

	if req.RepoPath != "/tmp/repo" {
		t.Error("RepoPath not set correctly")
	}
	if req.BranchName != "wolf/fix-sast" {
		t.Error("BranchName not set correctly")
	}
	if req.BaseBranch != "main" {
		t.Error("BaseBranch not set correctly")
	}
}

func TestParseSeverities(t *testing.T) {
	// buildPRBody should render severity in uppercase
	finding := models.Finding{
		Severity:  models.SeverityInfo,
		Title:     "Info finding",
		FilePath:  "readme.md",
		LineStart: 1,
	}
	req := PRRequest{
		Category: models.CategoryDocs,
		Findings: []models.Finding{finding},
	}
	body := buildPRBody(req)
	if !strings.Contains(body, "[INFO]") {
		t.Error("expected [INFO] in PR body")
	}
}
