package docs

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/alphabravocompany/thewolf/internal/scannertools/manifest"
)

func Markdown(m *manifest.Manifest) []byte {
	var b bytes.Buffer
	counts := m.TierCounts()
	fmt.Fprintln(&b, "# Scanner Tools")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "<!-- Generated by `go run ./cmd/scannertools docs`. Do not edit by hand. -->")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "Wolf scanner metadata is authored in `scanners/tools.yaml`. This table is generated from that manifest.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Counts")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| Tier | Count |")
	fmt.Fprintln(&b, "|---|---:|")
	fmt.Fprintf(&b, "| Default Wolf image | %d |\n", counts[manifest.TierDefault])
	fmt.Fprintf(&b, "| Wolf bucket images | %d |\n", counts[manifest.TierBucket])
	fmt.Fprintf(&b, "| Upstream/native images | %d |\n", counts[manifest.TierUpstream])
	fmt.Fprintf(&b, "| Total registered scanner tools | %d |\n", len(m.Tools))
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "## Tools")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "| Tool | Category | Tier | Version | Image or install | Platforms | Update source |")
	fmt.Fprintln(&b, "|---|---|---|---|---|---|---|")
	for _, name := range sortedByTierThenName(m) {
		tool := m.Tools[name]
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s | %s |\n",
			escape(name),
			escape(tool.Category),
			escape(tierLabel(tool)),
			escape(versionLabel(tool)),
			escape(sourceLabel(tool)),
			escape(platformLabel(tool)),
			escape(updateLabel(tool)),
		)
	}
	return b.Bytes()
}

func sortedByTierThenName(m *manifest.Manifest) []string {
	names := m.Names()
	order := map[string]int{
		manifest.TierUpstream: 0,
		manifest.TierDefault:  1,
		manifest.TierBucket:   2,
	}
	sort.SliceStable(names, func(i, j int) bool {
		a, b := m.Tools[names[i]], m.Tools[names[j]]
		if order[a.IntegrationTier] != order[b.IntegrationTier] {
			return order[a.IntegrationTier] < order[b.IntegrationTier]
		}
		return names[i] < names[j]
	})
	return names
}

func tierLabel(tool manifest.Tool) string {
	if tool.IntegrationTier == manifest.TierBucket && tool.Bucket != "" {
		return tool.Bucket + " bucket"
	}
	return tool.IntegrationTier
}

func versionLabel(tool manifest.Tool) string {
	if tool.PinnedVersion == "" {
		return "-"
	}
	if tool.VersionVariable == "" {
		return "`" + tool.PinnedVersion + "`"
	}
	return "`" + tool.PinnedVersion + "` (`" + tool.VersionVariable + "`)"
}

func sourceLabel(tool manifest.Tool) string {
	switch tool.IntegrationTier {
	case manifest.TierUpstream:
		if tool.Image.PinnedReference == "" {
			return "-"
		}
		return "`" + tool.Image.PinnedReference + "`"
	case manifest.TierBucket:
		return "`wolf-scanners-" + tool.Bucket + "`"
	default:
		if tool.Install.Manager == "" {
			return "`wolf-scanners`"
		}
		if tool.Install.Package == "" {
			return "`" + tool.Install.Manager + "`"
		}
		return "`" + tool.Install.Manager + ":" + tool.Install.Package + "`"
	}
}

func platformLabel(tool manifest.Tool) string {
	if tool.IntegrationTier != manifest.TierUpstream {
		return "-"
	}
	if len(tool.Image.Platforms) == 0 {
		return "`linux/amd64`, `linux/arm64`"
	}
	parts := make([]string, len(tool.Image.Platforms))
	for i, platform := range tool.Image.Platforms {
		parts[i] = "`" + platform + "`"
	}
	return strings.Join(parts, ", ")
}

func updateLabel(tool manifest.Tool) string {
	source := tool.UpdateSource
	switch source.Type {
	case "docker_registry":
		return "`docker:" + source.Repository + "`"
	case "github_releases":
		return "`github:" + source.Owner + "/" + source.Repo + "`"
	case "go_module":
		return "`go:" + source.Module + "`"
	case "rust_channel":
		return "`rust:" + source.Channel + "`"
	case "toolchain":
		return "`toolchain:" + source.Package + "`"
	case "debian_package":
		return "`debian:" + source.Package + "`"
	default:
		if source.Package != "" {
			return "`" + source.Type + ":" + source.Package + "`"
		}
		return "`" + source.Type + "`"
	}
}

func escape(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
